### ISSUE TITLE
Initial property editors - tidying

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#313]
We've got a first implementation of EMF-generated property editors.

This issue is a package of tidying, to include:
- source code formatting
- remove some unnecessary properties
- ensure properties are reflected in Chart renderer
- experiment with manipulating/removing axes

**Comment by IanMayo** [comment]
@theanuradha - you don't seem to have any more tickets.

I'd like to give you some tasks under this one, please - all related to the GEF editor.  Here's my progress:
![gefeditor](https://cloud.githubusercontent.com/assets/1108513/15513175/6ece34cc-21db-11e6-89c3-3da52efb8f6d.png)

I'd like you to make these fixes/improvements, please:
- There is now an "X" button to delete an axis.  Could you play with the layout so that the X appears next to the Axis title? (e.g. "Course" or "Depth").  
- For the above, could you also find the relevant listener so that the GEF editor updates? It currently only updates when dragging a dataset - not an axis.
- I've added processing so that it is possible to drag an axis from one chart to another - by dropping it onto existing axes.  But, could you wire up updates, so the GEF editor updates after the change is complete?
- In the GEF editor we have an "Axis" figure/element.  When we have several axes, they don't have a border. Could you play with the AxisEditPart diagram so that the Axis has a light-gray background shading?  There should also be a white border/margin between axes - which will show that there are several of them
- in your JFreeChart rendering, could you include a title for each chart, using the chart name? 

I'll push my branch **313_improve_properties** to your repo - so you can take commit to it.

**Comment by theanuradha** [comment]
> There is now an "X" button to delete an axis. Could you play with the layout so that the X appears next to the Axis title? (e.g. "Course" or "Depth").

![image](https://cloud.githubusercontent.com/assets/535713/15528619/35985f38-2263-11e6-8581-ef5d8dd2826f.png)

**Comment by theanuradha** [comment]
> For the above, could you also find the relevant listener so that the GEF editor updates? It currently only updates when dragging a dataset - not an axis.

done https://github.com/theanuradha/limpet/commit/e710d08b6f79080fc4fff43dbea336add08bd623

**Comment by theanuradha** [comment]
> I've added processing so that it is possible to drag an axis from one chart to another - by dropping it onto existing axes. But, could you wire up updates, so the GEF editor updates after the change is complete?

https://github.com/theanuradha/limpet/commit/642a4980c14373e06ec6ca84acc934d2a2a83750

**Comment by IanMayo** [comment]
Update works well, thanks.

**Comment by IanMayo** [comment]
More tasks for @theanuradha:
- [x] Make Axis label **Bold**
- [x] Put axis label closer to the Axis line (arrow)
- [ ] Make Chart title **Bold**

**Comment by IanMayo** [comment]
@theanuradha - we still have the minor issue in the above comment, to make the Chart Title bold in the GEF editor tab.

**Comment by IanMayo** [comment]
Ok, closing this - we're on top of it.
